#!/bin/bash

SOURCE_DIR="/downloads"
FILM_DIR="${SOURCE_DIR}/Movies"
SERIE_DIR="${SOURCE_DIR}/Shows"

[ ! -d "$FILM_DIR" ] && mkdir -p "$FILM_DIR"
[ ! -d "$SERIE_DIR" ] && mkdir -p "$SERIE_DIR"

# Extensions vidéo à considérer
EXTENSIONS="mp4|mkv|avi|mov"

# Parcourir tous les fichiers vidéo
find "$SOURCE_DIR" -type f -regextype posix-extended -regex ".*\.($EXTENSIONS)$" | while read -r file; do
  filename=$(basename "$file")
  src_file=$(echo $file | sed -e "s/^\/downloads/\.\./g")

  # Organisation des FILMS
  if echo "$filename" | grep -Eiq 'S[0-9]{1,2}E[0-9]{1,2}|[0-9]{1,2}x[0-9]{1,2}'; then
    # C'est une série, on ignore
    echo "" > /dev/null 2>&1
  elif echo "$file" | grep -Eiq 'Apps'; then
    # C'est une application, on ignore
    echo "" > /dev/null 2>&1
  else
    target="$FILM_DIR/$filename"
    if [ ! -e "$target" ]; then
      ln -s "$src_file" "$target"
    fi
  fi
done

# Organisation des SERIES
find "$SOURCE_DIR" -maxdepth 1 -type d -iregex '.*/.*\(s[0-9][0-9]*\|season[ _]*[0-9][0-9]*\).*' -exec basename {} \; | while read -r dir; do
  [ ! -d ${SERIE_DIR}/"$dir" ] && mkdir -p ${SERIE_DIR}/"$dir"

  # Parcourir tous les fichiers vidéo de la SERIE
  find "$SOURCE_DIR/$dir" -type f -regextype posix-extended -regex ".*\.($EXTENSIONS)$" | while read -r file; do
    filename=$(basename "$file")
    src_file=$(echo $file | sed -e "s/^\/downloads/\.\.\/\.\./g")

    # Organisation des SERIES
    if echo "$filename" | grep -Eiq 'E[0-9]{1,2}|[0-9]{1,2}x[0-9]{1,2}'; then
      target="$SERIE_DIR/$dir/$filename"
      if [ ! -e "$target" ]; then
        ln -s "$src_file" "$target"
      fi
    fi
  done
done
